### Criar paciente
POST http://localhost:3000/api/pacientes
Content-Type: application/json

{
  "nome": "Maria Souza",
  "data_nascimento": "1980-04-10",
  "email": "maria@gmail.com",
  "telefone": "11999999999"
}

### Listar pacientes
GET http://localhost:3000/api/pacientes

### Editar paciente
PUT http://localhost:3000/api/pacientes/1c7afc93-437f-46c5-b699-6bd6394868e3
Content-Type: application/json

{
  "nome": "Maria S. Souza",
  "data_nascimento": "1980-04-10",
  "email": "maria.s@example.com",
  "telefone": "11988888888"
}

### Deletar paciente
DELETE http://localhost:3000/api/pacientes/01af82de-534d-4911-b221-5affce20c010

### Criar médico
POST http://localhost:3000/api/medicos
Content-Type: application/json

{
    "nome": "Dr. João Alencar",
    "especialidade": "Cardiologia",
    "email": "joao.alencarr@gmail.com",
    "telefone": "11912345678"
}

### Listar médicos
GET http://localhost:3000/api/medicos

### Editar médico
PUT http://localhost:3000/api/medicos/f32b3bab-1cb1-4335-b7aa-70e7320821c2
Content-Type: application/json

{
    "nome": "Dr. João A.",
    "especialidade": "Cardiologia",
    "email": "joao.alencarr@gmail.com",
    "telefone": "11987654321"
}

### Deletar médico
DELETE http://localhost:3000/api/medicos/f2eac5c2-f706-496e-a8df-ff3f1916c454

### Criar consulta
POST http://localhost:3000/api/consultas
Content-Type: application/json

{
    "paciente_id": "1c7afc93-437f-46c5-b699-6bd6394868e3",
    "medico_id": "f32b3bab-1cb1-4335-b7aa-70e7320821c2",
    "data_consulta": "2025-06-01T10:30:00",
    "motivo": "Consulta de rotina",
    "observacoes": "Primeira consulta"
}
### Listar consultas
GET http://localhost:3000/api/consultas

### Editar consulta
PUT http://localhost:3000/api/consultas/c7d97555-afda-4d6a-8c00-041b2944556b
Content-Type: application/json

{
    "paciente_id": "1c7afc93-437f-46c5-b699-6bd6394868e3",
    "medico_id": "f2eac5c2-f706-496e-a8df-ff3f1916c454",
    "data_consulta": "2025-06-01T11:00:00Z",
    "motivo": "Dor no peito persistente",
    "observacoes": "Reagendada - Paciente solicitou alteração"
}

### Deletar consulta
DELETE http://localhost:3000/api/consultas/244a3576-6b70-4d01-a4aa-40fa9f226c2f